#index:
#    path: /
#    controller: App\Controller\DefaultController::index




fos_user_security_login:
   path: /login
   methods: [GET, POST]
   defaults: { _controller: 'App\Controller\UserController::getUserByUsernameAction' }

fos_user_security_check:
   path: /login_check
   methods: [POST]
   defaults: { _controller: fos_user.security.controller:checkAction }

fos_user_security_logout:
   path: /logout
   methods: [GET, POST]
   defaults: { _controller: fos_user.security.controller:logoutAction }